name: webscoket_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^2.1.0

  socket_io_client: ^2.0.3+1
  #socket_io_client: ^1.0.2
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.1.2
  get: ^4.6.6
  google_mobile_ads: ^5.1.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/theme/
    - assets/lottie/json/


# Extention name: Flutter Assets Gen : https://marketplace.visualstudio.com/items?itemName=weekit.flutter-assets-gen2
# Add this to auto-generate assets in lib/constants/assets.dart
flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix: